name: scally
version: '${project.version}'
main: com.scally.serverutils.ServerUtils
api-version: 1.19

commands:
  bootstrap:
    description: Bootstraps hotbar with Creative-mode items
    usage: /bootstrap

  paul:
    description: Paul's Bootstraps hotbar with Creative-mode items
    usage: /paul

  slabs:
    description: Replace slabs
    usage: /slabs <x1> <y1> <z1> <x2> <y2> <z2> <from-slab> <to-slab>
    
  stairs:
    description: Replace stairs
    usage: /stairs <x1> <y1> <z1> <x2> <y2> <z2> <from-stair> <to-stair>

  trapdoors:
    description: Replace trapdoors
    usage: /trapdoors <x1> <y1> <z1> <x2> <y2> <z2> <from-trapdoor> <to-trapdoor>

  fill-container:
    description: Fill a container with a random distribution
    usage: /fill-container <x> <y> <z> <distribution>

  s-undo:
    description: Undo last command(s)
    usage: /s-undo [int]

  walls:
    description: Replace walls
    usage: /walls <x1> <y1> <z1> <x2> <y2> <z2> <from-wall> <to-wall>

  blocks:
    description: Replace all types of blocks
    usage: /blocks <x1> <y1> <z1> <x2> <y2> <z2> <from-block> <to-block>
