name: scally
version: '${project.version}'
main: com.scally.serverutils.ServerUtils
api-version: 1.19
softdepend: [WorldEdit]

commands:
  bootstrap:
    description: Bootstraps hotbar with Creative-mode items
    usage: /bootstrap

  paul:
    description: Paul's Bootstraps hotbar with Creative-mode items
    usage: /paul

  slabs:
    description: Replace slabs
    usage: /slabs <x1> <y1> <z1> <x2> <y2> <z2> <from-slab> <to-slab> | /slabs we <from-slab> <to-slab>
    
  stairs:
    description: Replace stairs
    usage: /stairs <x1> <y1> <z1> <x2> <y2> <z2> <from-stair> <to-stair> | /stairs we <from-stair> <to-stair>

  trapdoors:
    description: Replace trapdoors
    usage: /trapdoors <x1> <y1> <z1> <x2> <y2> <z2> <from-trapdoor> <to-trapdoor> | /trapdoors we <from-trapdoor> <to-trapdoor>

  fill-container:
    description: Fill a container with a random distribution
    usage: /fill-container <x> <y> <z> <distribution>

  fill-containers:
    description: Fill all containers in a volume with a random distribution
    usage: /fill-containers <block> <x1> <y1> <z1> <x2> <y2> <z2> <distribution>

  s-undo:
    description: Undo last command(s)
    usage: /s-undo [int]

  walls:
    description: Replace walls
    usage: /walls <x1> <y1> <z1> <x2> <y2> <z2> <from-wall> <to-wall> | /walls we <from-wall> <to-wall>

  logs:
    description: Replace logs
    usage: /logs <x1> <y1> <z1> <x2> <y2> <z2> <from-log> <to-log> | /logs we <from-log> <to-log>

  blocks:
    description: Replace all types of blocks
    usage: /blocks <x1> <y1> <z1> <x2> <y2> <z2> <from-block> <to-block> | /blocks we <from-block> <to-block>

  dist:
    description: Save and retrieve block distribution strings
    usage: /dist list [player] | /dist get <name> | /dist get <player> <name> | /dist save <name> <distribution> | /dist update <name> <distribution> | /dist delete <name>
    permission: scally.dist.read

permissions:
  scally.dist.read:
    description: List and get saved distributions for any player
    default: true
  scally.dist.write:
    description: Save, update, or delete your own distributions
    default: true
