name: scally
version: '${project.version}'
main: com.scally.serverutils.ServerUtils
api-version: 1.19

commands:
  slabs:
    description: Replace slabs
    usage: /slabs <x1> <y1> <z1> <x2> <y2> <z2> <from-slab> <to-slab>
    
  stairs:
    description: Replace stairs
    usage: /stairs <x1> <y1> <z1> <x2> <y2> <z2> <from-stair> <to-stair>

  fill-container:
    description: Fill a container with a random distribution
    usage: /fill-container <x> <y> <z> <distribution>