# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # TODO: don't hardcode the JAR name
    - name: Move JAR
      run: |
        mkdir ftp
        mv ./target/server-utils-1.0-SNAPSHOT.jar ./ftp

    - name: Upload JAR
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER_IP }}
        username: ${{ secrets.FTP_SERVER_USERNAME }}
        password: ${{ secrets.FTP_SERVER_PASSWORD }}
        local-dir: "./ftp/"
        server-dir: "/plugins/"

